### ISSUE TITLE
Really splendid

### ISSUE THREAD

**Issue by IvanDeFelice76** [theRealPadster/Mist-theme#10]
Is it possible, however, to create a compact version for gnome-shell 3.30 with smaller menus and calendars?

It would be great for Fedora, but on a 1366x768 (16.9) monitor the menus are really disproportionate!!!

**Comment by theRealPadster** [comment]
I'm glad you like it, however I'm not really sure how to go about creating and maintaining two versions. I wrote this theme a long time ago and do not recall what all the different padding values and such are, so it would be some undertaking, and I do not currently have the time. Feel free to poke through the css and tweak the padding values if you can find them.

**Comment by IvanDeFelice76** [comment]
> Sono contento che ti piaccia, tuttavia non sono sicuro di come creare e mantenere due versioni. Ho scritto questo tema molto tempo fa e non ricordo quali sono i diversi valori di padding e simili, quindi sarebbe un po 'impegnativo, e al momento non ho tempo. Sentiti libero di sondare il css e modificare i valori del padding se riesci a trovarli.
If I had the capacity to do it, I would have done it....

Too bad because it is perhaps the best arrangement ... but menu and calendar too big
