### ISSUE TITLE
Multi Monitor add-on

### ISSUE THREAD

**Issue by jarek102** [theRealPadster/Mist-theme#6]
With multiple monitors desktop thumbnails are not styled:
![screenshot from 2016-02-15 05-21-16](https://cloud.githubusercontent.com/assets/491716/13039796/1d4e19c6-d3a4-11e5-8902-20f170ad5e3f.png)

**Comment by theRealPadster** [comment]
How do you have your shell set up to handle multiple monitors? Mine only shows the one sidebar like in your left side. Is it a tweak-tool thing or an extension?

**Comment by jarek102** [comment]
It is extension:
https://github.com/spin83/multi-monitors-add-on
probobly fault of https://github.com/spin83/multi-monitors-add-on/blob/master/multi-monitors-add-on%40spin83/stylesheet.css

Unfortunately i don't think extension will support different themes, that's why i filed bug here.

**Comment by theRealPadster** [comment]
@jarek102 The extension  gave me an error when I tried to use it, but I think this commit (cf42b18) should fix it. Can you try it out?

**Comment by jarek102** [comment]
It looks like style was not overridden.
I don't know about gnome themeing but you can im me at jarek102(remove me)@gmail.com

**Comment by theRealPadster** [comment]
I remember someone posted about overriding extension stylesheets [here on Google+](https://plus.google.com/u/0/106773314255716729881/posts/117B2X5rwrx). It might not be possible to override  the extension. I suppose you could edit the extension's stylesheet with the CSS I added?
